# Generated by Django 2.0.5 on 2018-06-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_activity_subhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_off',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, null=True, verbose_name='折扣'),
        ),
    ]
