# Generated by Django 2.0.6 on 2018-06-28 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20180627_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.TemplateCategory', verbose_name='归属')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
                'db_table': 'templatecategory',
            },
        ),
    ]
