# Generated by Django 2.0.6 on 2018-06-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_templatecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='code',
            field=models.CharField(default='1000', max_length=6),
            preserve_default=False,
        ),
    ]
