# Generated by Django 2.0.6 on 2018-06-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_templatecategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_status',
            field=models.CharField(choices=[('1000', '销售'), ('0001', '入库'), ('0010', '调入'), ('0100', '调出')], default='1000', max_length=4, verbose_name='分类'),
        ),
    ]
