# Generated by Django 2.0.6 on 2018-06-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20180628_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_status',
            field=models.CharField(choices=[('000101', '销售'), ('100001', '入库'), ('011001', '调入'), ('011002', '调出')], default='1000', max_length=6, verbose_name='分类'),
        ),
    ]
