# Generated by Django 2.0.6 on 2018-06-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20180628_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Position', verbose_name='门店'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_status',
            field=models.CharField(choices=[('000101', '入库'), ('100001', '销售'), ('011001', '调入'), ('011002', '调出')], default='1000', max_length=6, verbose_name='分类'),
        ),
    ]
