# Generated by Django 2.0.6 on 2018-06-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20180628_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_code',
            field=models.CharField(default=123, max_length=6, verbose_name='编号'),
            preserve_default=False,
        ),
    ]
