# Generated by Django 2.0.6 on 2018-06-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_position_position_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_code', models.CharField(max_length=16, verbose_name='批号')),
                ('patch_product', models.DateField(verbose_name='生产日期')),
                ('patch_validity', models.DateField(verbose_name='有效日期')),
                ('patch_commdity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Commdity', verbose_name='商品')),
            ],
            options={
                'verbose_name': '批号',
                'verbose_name_plural': '批号',
                'db_table': 'patch',
            },
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_product',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_validity',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Patch', verbose_name='批号'),
        ),
    ]
