# Generated by Django 2.0.6 on 2018-06-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_auto_20180628_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_validity',
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Patch', verbose_name='批号'),
        ),
    ]
