# Generated by Django 2.0.6 on 2018-06-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_auto_20180628_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='created',
        ),
    ]
